# deployment db
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dvwa-secret
              key: db_pass
        - name: MYSQL_DATABASE
          value: dvwa
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: dvwa-secret
              key: db_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dvwa-secret
              key: db_pass
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
  