apiVersion: v1
kind: ConfigMap
metadata:
  name: dvwa-config
  namespace: training
data:
  db_host: mysql-service 

---
apiVersion: v1
kind: Secret
metadata:
  name: dvwa-secret
  namespace: training
type: Opaque
data:
  db_user: YXBw  # "app" en Base64
  db_pass: cGFzc3dvcmQxMjM=  # "password123" en Base64

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: training
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: training
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dvwa-secret
              key: db_pass
        - name: MYSQL_DATABASE
          value: dvwa
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: dvwa-secret
              key: db_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dvwa-secret
              key: db_pass
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: training
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
  namespace: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: vulnerables/web-dvwa
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dvwa-config
              key: db_host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dvwa-secret
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: dvwa-secret
              key: db_pass
        - name: DB_DATABASE
          value: dvwa
        - name: DB_PORT
          value: "3306"
        - name: DEFAULT_SECURITY_LEVEL
          value: "impossible"
        - name: DEFAULT_LOCALE
          value: "en"

---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
  namespace: training
spec:
  selector:
    app: dvwa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dvwa-to-db
  namespace: training
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: dvwa
    ports:
    - protocol: TCP
      port: 3306
