name: Deploy DVWA

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubeval
        run: |
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo mv kubeval /usr/local/bin/

      - name: Validate Kubernetes YAML files
        run: |
          kubeval --strict manifests/*.yaml

      - name: Security scan with kubesec (Docker)
        run: |
          docker run --rm -v $(pwd)/manifests:/manifests controlplaneio/kubesec scan /manifests/*.yaml

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan images with Trivy (with exit code handling)
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL --format json vulnerables/web-dvwa > trivy_web_dvwa_results.json || echo "Trivy scan for web-dvwa failed" > trivy_web_dvwa_results.json
          trivy image --exit-code 1 --severity HIGH,CRITICAL --format json mysql:5.7 > trivy_mysql_results.json || echo "Trivy scan for mysql:5.7 failed" > trivy_mysql_results.json

      - name: Upload Trivy results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: |
            trivy_web_dvwa_results.json
            trivy_mysql_results.json

  check-errors:
    name: Check Errors in Trivy Scan Results
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Trivy results for errors
        run: |
          if grep -q '"severity": "HIGH"\|"severity": "CRITICAL"' trivy_web_dvwa_results.json; then
            echo "Critical vulnerabilities found in web-dvwa!"
            exit 1
          else
            echo "No critical vulnerabilities found in web-dvwa."
          fi
          if grep -q '"severity": "HIGH"\|"severity": "CRITICAL"' trivy_mysql_results.json; then
            echo "Critical vulnerabilities found in mysql!"
            exit 1
          else
            echo "No critical vulnerabilities found in mysql."
          fi
