name: Deploy DVWA

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubeval
        run: |
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo mv kubeval /usr/local/bin/

      - name: Validate Kubernetes YAML files
        run: |
          kubeval --strict manifests/*.yaml > kubeval_results.txt
        continue-on-error: true  

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan images with Trivy
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL vulnerables/web-dvwa > trivy_results_web-dvwa.txt
          trivy image --exit-code 1 --severity HIGH,CRITICAL mysql:5.7 > trivy_results_mysql.txt
        continue-on-error: true 

      - name: Verificar archivos en el directorio manifests
        run: |
          ls -la $(pwd)/manifests

      - name: Security scan with kubesec (Docker)
        run: |
          # Usar la ruta directa para evitar el error "no such file"
          docker run --rm -v $(pwd)/manifests:/manifests kubesec/kubesec:v2 scan /manifests/prueba.yaml > kubesec_results.txt
        continue-on-error: true  

      - name: Upload Kubeval Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubeval-results
          path: kubeval_results.txt

      - name: Upload Trivy Results (web-dvwa) as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results-web-dvwa
          path: trivy_results_web-dvwa.txt

      - name: Upload Trivy Results (mysql) as Artifact
        if: exists('trivy_results_mysql.txt')
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results-mysql
          path: trivy_results_mysql.txt

      - name: Upload Kubesec Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubesec-results
          path: kubesec_results.txt
